### ISSUE TITLE
Sentiment analysis problem

### ISSUE THREAD

**Issue by sadanyh** [adhaamehab/textblob-ar#19]
Hi,

Could you please suggest solution for the **.sentiment** function error
'HTTP Error 429: Too Many Requests'. 
It was working fine but then whenever I run it, this error pops up. I was thinking that it must be the textblob-ar is using an API like Google and I need some cool off period, but I tried after leaving it for a whole day. Still the problem is the same.

Thank you

**Comment by khaledalaneziq8** [comment]
Hi @sadanyh ... I had the same issue. After some Googling it turned out that this is a limit for the Google translate API which limits users to 1000 calls per day. It is really frustrating if true.

@adhaamehab Is there any workaround for this?

**Comment by adhaamehab** [comment]
Sorry guys, this is limit in google translate api. There is now workaround.

**Comment by khaledalaneziq8** [comment]
Maybe it would have been better to have this limitation in the library description stated at the landing page. Sadly, after investing some time in installation & coding I was surprised by it.
